name: Maven Build and Test ON PR

on:
  pull_request:
    branches:
      - '**'  # Matches pull requests to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify your desired JDK version
          distribution: 'temurin'  # Use 'temurin' for OpenJDK

      - name: Build with Maven
        run: mvn clean install
